### ISSUE TITLE
State of the field

### ISSUE THREAD

**Issue by jgonggrijp** [distant-viewing/dvt#16]
This issue is part of my review in https://github.com/openjournals/joss-reviews/issues/1800.

One of the requirements on the paper is to describe how your package compares to other commonly-used packages. Currently, the second paragraph of the summary mentions the existence of numerous standalone algorithm implementations but “limited options” for building end-to-end pipelines. It may be valuable to name these limited options explicitly and discuss their relative advantages and disadvantages.

**Comment by statsmaths** [comment]
Thanks for pointing out this place for adding better references. The sentence now reads:

> However, there are limited options for users looking to quickly build end-to-end pipelines that link together common visual annotations. Those tools that do exist focus on specific subtasks, such as as FaceNet’s recognition of faces (Schroff, Kalenichenko, & Philbin, 2015), visual embedding with PixPlot (Duhaime, 2019), and FilmColors’ analysis of color (Flueckiger & Halter, 2018).
