### ISSUE TITLE
Improve documentation for layperson and Mac users

### ISSUE THREAD

**Issue by elektrobohemian** [distant-viewing/dvt#18]
Generally speaking, the documentation is very well-written. As the software also focusses on layperson users, some parts of the documentation should be expanded.

* Although the docs clearly state that the software was built and test on Python 3.7 it should be put more clearly that it actually need Python 3.7 (or above) as the installation scripts strictly check for this requirement.
* As the documentation contains shell commands to be copy and pasted, it should clarify that they rely on bash. For instance, Mac users (now with zsh as a standard) will not suceed on running all snippets. "pip install .[tests,optional]" will yield "zsh: no matches found: .[tests,optional]" and should be run with bash. This is less critical, as test will mainly run by developers who will easily cope with this issue.

**Comment by statsmaths** [comment]
I had not realised the issue with zsh. I fixed the code by escaping the brackets and
it runs for me now on bash and zsh. I also further clarified the role of Python 3.7 
(its required) and Anaconda (recommended, but also possible to use a virtual
environment). Should be fixed now with 116ef22.
