### ISSUE TITLE
Improve consistency of documentation

### ISSUE THREAD

**Issue by elektrobohemian** [distant-viewing/dvt#20]
### (I am refering to the end-user documentation on Github)

* The "low-level" tutorial refers to two files (ainput="video-clip.wav",
  sinput="video-clip.srt") which have to be copied from tests/test-data/ to the working directory as the mp4 file stated above. Otherwise, the tutorial will fail if you strictly follow the instructions.
* Under Mac OS, I could not reproduce the values quoted in the tutorial probably due to rounding issues. The documentation should discuss this issue.

### (I am refering to the program documentation on https://distant-viewing.github.io/dvt/))

* Example analysis using aggregated metadata: “Visual Style in Two Network Era Sitcoms” refers to a dead link (https://doi.org/10.22148/16.043)

**Comment by statsmaths** [comment]
Thanks. Now fixed with b849dda.

The dead paper link is quite annoying because this is supposed to be the whole point of
DOIs. The journal rearranged their website last month but still haven't fixed the DOI redirects.
