### ISSUE TITLE
Make Anaconda a strict requirement in the documentation

### ISSUE THREAD

**Issue by elektrobohemian** [distant-viewing/dvt#21]
To simulate to different usage scenarios, I tried to install the software on two plattforms:
* Ubuntu 18.04.3 LTS with Python 3.6
* Mac OS 10.14.6 with Anaconda Python 3.7

### Ubuntu
* LTS comes with Python 3.6 pre-installed, hence the documentation should address this requirement (see other issue)
* After upgrading to 3.7 and PIP3, the installation of DVT fails due to numerous issues which might be in parts caused by Ubuntu
* when using Anaconda under Ubuntu, it becomes possible to install dvt

### Mac OS
* installation with Anaconda succeeds, however the tutorial yields other values (see other issues)
* minor problems with zsh and running tests

**Comment by jgonggrijp** [comment]
It might have been possible to avoid the problems on Ubuntu by using a virtualenv. However, this is also something that the tutorial doesn't mention (yet).

**Comment by statsmaths** [comment]
As with issue #18, other than the macOS web server issue mentioned elsewhere, I think
this is solved with 116ef22. I now mention that 3.7 is required, recommend Anaconda 
Python, and also mentioned that a clean virtual environment should work as well.
