### ISSUE TITLE
Error running example face annotation code 

### ISSUE THREAD

**Issue by rlskoeser** [distant-viewing/dvt#34]
I'm trying to run the face annotation code example in the readme and getting errors. I think I have everything installed correctly. I've tried in Google Colab, jupyter, and python console, so I don't think it's my environment.  

Here's the error from running `dvt.AnnoFaces()` in a jupyter notebook:
```
Downloading: "https://github.com/distant-viewing/dvt/releases/download/0.0.1/dvt_detect_face.pt" to /Users/rkoeser/.cache/torch/hub/checkpoints/dvt_detect_face.pt

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[3], line 1
----> 1 anno_face = dvt.AnnoFaces()

File ~/workarea/env/dvt/lib/python3.9/site-packages/dvt/face.py:32, in AnnoFaces.__init__(self, model_path_mtcnn, model_path_vggface)
     29 def __init__(self, model_path_mtcnn=None, model_path_vggface=None):
     31     if not model_path_mtcnn:
---> 32         model_path_mtcnn = _download_file("dvt_detect_face.pt")
     34     if not model_path_vggface:
     35         model_path_vggface = _download_file("dvt_face_embed.pt")

File ~/workarea/env/dvt/lib/python3.9/site-packages/dvt/utils.py:131, in _download_file(url, basename)
    129     r = HASH_REGEX.search(filename)  # r is Optional[Match[str]]
    130     hash_prefix = r.group(1) if r else None
--> 131     download_url_to_file(url, cached_file, hash_prefix, progress=True)
    133 return cached_file

File ~/workarea/env/dvt/lib/python3.9/site-packages/torch/hub.py:611, in download_url_to_file(url, dst, hash_prefix, progress)
    609 dst = os.path.expanduser(dst)
    610 dst_dir = os.path.dirname(dst)
--> 611 f = tempfile.NamedTemporaryFile(delete=False, dir=dst_dir)
    613 try:
    614     if hash_prefix is not None:

File ~/.pyenv/versions/3.9.13/lib/python3.9/tempfile.py:545, in NamedTemporaryFile(mode, buffering, encoding, newline, suffix, prefix, dir, delete, errors)
    542 if _os.name == 'nt' and delete:
    543     flags |= _os.O_TEMPORARY
--> 545 (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    546 try:
    547     file = _io.open(fd, mode, buffering=buffering,
    548                     newline=newline, encoding=encoding, errors=errors)

File ~/.pyenv/versions/3.9.13/lib/python3.9/tempfile.py:255, in _mkstemp_inner(dir, pre, suf, flags, output_type)
    253 _sys.audit("tempfile.mkstemp", file)
    254 try:
--> 255     fd = _os.open(file, flags, 0o600)
    256 except FileExistsError:
    257     continue    # try again

FileNotFoundError: [Errno 2] No such file or directory: '/Users/rkoeser/.cache/torch/hub/checkpoints/tmp3fu4p_3n'
```

I can't tell where it's going wrong, but hopefully this is meaningful to you.  I tested manually and the `.pt` file does download.

Is there a reason these files are separate downloads? Would it make sense to include them as part of the python package?

**Comment by freeshrugsxd** [comment]
Hey, the problem is that the requests library cannot handle backspaces in URLs and in the utils.py there is a line where a base-URL is concatenated with a file name using `os.path.join` which, on Windows, uses a backslash as seperator. So you end up with a URL that looks like this: 
https://github.com/distant-viewing/dvt/releases/download/0.0.1\\dvt_detect_face.pt

which fails, because requests.get('https://github.com/distant-viewing/dvt/releases/download/0.0.1\\dvt_detect_face.pt') returns 404.

To fix this, change this line:

https://github.com/distant-viewing/dvt/blob/dea8bbff2f798e1a480123a28016cb4ac8dce062/dvt/utils.py#L121

into something like this:

`url = basename + '/' url` or `url = f'{basename}/{url}'`

**Comment by rlskoeser** [comment]
confirmed that #36 resolved this problem by installing main branch in colab and running example steps from the readme

thanks @freeshrugsxd for identifying a solution for part of the problem
