### ISSUE TITLE
please consider updating PyPI

### ISSUE THREAD

**Issue by cameron-simpson** [distant-viewing/dvt#37]
The version on PyPI is 1.0.0 still although the github repo shows 1.0.1. If the most recent commits (PR 36 merge) are considered good, maybe even do a 1.0.2 release?

Disclaimer: I'm not using `dvt` but someone on `discuss.python.org` was asking about an install problem and I noticed they were getting `dvt` from github instead of PyPI (still using `pip` but with a github URL). I was hoping to suggest to them they could just `pip install dvt`.

Thank you.

**Comment by statsmaths** [comment]
Thank you. Yes, it took forever for me to get an issue with PyPI fixed but I just updated it to the most recent version. Should be updated more regularly now.

**Comment by cameron-simpson** [comment]
Thank you! - Cameron
